from fpdf import FPDF
from PIL import Image
from xhtml2pdf import pisa
import io
import base64
import os

# Method A: Traditional FPDF manual typesetting
def create_manual_pdf(data, img_b64=None):
    pdf = FPDF()
    pdf.set_auto_page_break(auto=True, margin=15)
    
    pdf.add_page()
    pdf.set_fill_color(15, 23, 42) 
    pdf.rect(0, 0, 210, 297, 'F') 
    
    pdf.set_text_color(255, 255, 255)
    pdf.set_font("Helvetica", 'B', 32)
    pdf.set_y(80)
    pdf.cell(0, 15, "GAME DESIGN", ln=True, align='C')
    pdf.cell(0, 15, "SPECIFICATION", ln=True, align='C')
    
    pdf.set_font("Helvetica", '', 20)
    pdf.ln(20)
    
    title = data.get('name', 'Untitled').encode('latin-1', 'replace').decode('latin-1')
    pdf.cell(0, 10, title, ln=True, align='C')
    
    if img_b64:
        try:
            img_data = base64.b64decode(img_b64)
            img_io = io.BytesIO(img_data)
            img = Image.open(img_io)
            pdf.image(img, x=45, y=160, w=120) 
        except Exception:
            pass 
            
    pdf.add_page()
    pdf.set_text_color(0, 0, 0)
    
    def body_text(txt):
        pdf.set_font("Helvetica", '', 11)
        safe_txt = str(txt).encode('latin-1', 'replace').decode('latin-1')
        pdf.multi_cell(0, 6, safe_txt)
        pdf.ln(3)

    pdf.set_font("Helvetica", 'B', 14)
    pdf.cell(0, 10, "1. Executive Summary", ln=True)
    body_text(f"Genre: {data.get('name')}")
    body_text(f"Concept: {data.get('details', {}).get('release_blurb', '')}")
    pdf.ln(5)
    
    pdf.set_font("Helvetica", 'B', 14)
    pdf.cell(0, 10, "2. Mechanics", ln=True)
    body_text(data.get('details', {}).get('core_loop', ''))

    return pdf.output(dest='S').encode('latin-1')

# Method B: HTML to PDF (AI Design Solution)
def convert_html_to_pdf(html_content):
    """
    Use xhtml2pdf to convert the HTML string generated by AI into a PDF binary stream.
    """
    pdf_output = io.BytesIO()
    
    try:
        pisa_status = pisa.CreatePDF(
            io.StringIO(html_content),
            dest=pdf_output
        )
        
        if pisa_status.err:
            print("PDF Generation Failed")
            return b""
            
        return pdf_output.getvalue()
        
    except Exception as e:
        print(f"转换异常: {e}")
        return b""

# Fallback method: Should the AI fail to generate the HTML template
def get_fallback_html(data):
    return f"""
    <html>
    <head>
        <style>
            body {{ font-family: Helvetica, sans-serif; padding: 40px; color: #333; }}
            h1 {{ color: #2563eb; border-bottom: 2px solid #2563eb; padding-bottom: 10px; }}
            .box {{ background: #f1f5f9; padding: 20px; border-radius: 10px; margin-top: 20px; }}
        </style>
    </head>
    <body>
        <h1>{data.get('name')}</h1>
        <p><strong>Status:</strong> AI Layout Generation Failed (Using Fallback)</p>
        <div class="box">
            <h3>Core Concept</h3>
            <p>{data.get('details', {}).get('release_blurb', '')}</p>
        </div>
    </body>
    </html>
    """
